source $HOME/.vim/cfg/plugins.vimrc
source $HOME/.vim/cfg/general.vimrc
source $HOME/.vim/cfg/keybindings.vimrc

source $HOME/.vim/cfg/include/airline.vim
source $HOME/.vim/cfg/include/ctrlp-telescope.vim
source $HOME/.vim/cfg/include/lspconfig.vim
source $HOME/.vim/cfg/include/neoformat.vim
source $HOME/.vim/cfg/include/nerdtree.vim
source $HOME/.vim/cfg/include/filetypes.vim
