require('core.plugins.gruvbox')
require('core.plugins.harpoon')
require('core.plugins.lualine')
require('core.plugins.nvim-tree')
require('core.plugins.telescope')
require('core.plugins.treesitter')
require('core.plugins.undotree')
